### ISSUE TITLE
1.1.1版本kafka设置分区数量partitionsNum没用

### ISSUE THREAD

**Issue by panjianping** [alibaba/canal#1174]
请问是否要将 flatMessage 设置为 true 才会生效？
```yml
servers: localhost:9092
retries: 1
batchSize: 16384
lingerMs: 1
bufferMemory: 33554432

# Canal的batch size, 默认50K, 由于kafka最大消息体限制请勿超过1M(900K以下)
canalBatchSize: 50
# Canal get数据的超时时间, 单位: 毫秒, 0为不限超时
canalGetTimeout: 100
# 是否为json格式 如果设置为false,对应MQ收到的消息为protobuf格式 需要通过CanalMessageDeserializer进行解码
flatMessage: false

canalDestinations:
  - canalDestination: house
    topic: house
    #partition: 0
    #对应topic分区数量
    partitionsNum: 3
    partitionHash:
        users.user: id
```
