### ISSUE TITLE
请问adapter rocketmq客户端连接报错的原因是什么

### ISSUE THREAD

**Issue by Near-Zhang** [alibaba/canal#1200]
报错信息:
>2018-11-27 15:55:50.992  INFO 3461 --- [       Thread-4] c.a.o.c.a.l.l.CanalAdapterRocketMQWorker : =============> Start to connect topic: example <=============
2018-11-27 15:55:50.993  INFO 3461 --- [       Thread-4] c.a.o.c.a.l.l.CanalAdapterRocketMQWorker : =============> Start to subscribe topic: example<=============
2018-11-27 15:55:50.993  INFO 3461 --- [       Thread-4] c.a.o.c.a.l.l.CanalAdapterRocketMQWorker : =============> Subscribe topic: example succeed<=============
2018-11-27 15:55:51.094 ERROR 3461 --- [       Thread-4] c.a.o.c.a.l.l.CanalAdapterRocketMQWorker : null
>java.lang.NullPointerException: null
        at com.alibaba.otter.canal.client.rocketmq.RocketMQCanalConnector.ack(RocketMQCanalConnector.java:219) ~[canal.client-1.1.2-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.mqWriteOutData(AbstractCanalAdapterWorker.java:152) ~[client-adapter.launcher-1.1.2-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterRocketMQWorker.process(CanalAdapterRocketMQWorker.java:64) ~[client-adapter.launcher-1.1.2-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]

配置文件application.yml:
``` yml
server:
  port: 8081
logging:
  level:
    org.springframework: WARN
    com.alibaba.otter.canal.client.adapter.rdb: DEBUG
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
canal.conf:
  zookeeperHosts: 127.0.0.1:2181
  mqServers: 127.0.0.1:9876
  flatMessage: true
  retries: 0
  timeout:
  mqTopics:
  - mqMode: rocketmq
    topic: example
    groups:
    - groupId: g2
      outAdapters:
      - name: rdb
        key: mysql
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver
          jdbc.url: jdbc:mysql://127.0.0.1:3306
          jdbc.username: root
          jdbc.password:************
          threads: 5
          commitSize: 5000
```
