### ISSUE TITLE
canal_adapter 消费消息失败

### ISSUE THREAD

**Issue by Near-Zhang** [alibaba/canal#1219]
成功获取了 mq 里面的消息，但是消费失败
错误日志：
>2018-11-29 10:48:32.404  INFO 23489 --- [MessageThread_1] c.a.o.c.c.r.RocketMQCanalConnector       : Get Message:[MessageExt [queueId=0, storeSize=334, queueOffset=59, sysFlag=0, bornTimestamp=1543459712393, bornHost=/192.168.0.28:34196, storeTimestamp=1543459712397, storeHost=/192.168.0.28:10911, msgId=C0A8001C00002A9F0000000000007633, commitLogOffset=30259, bodyCRC=868347517, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message{topic='example', flag=0, properties={MIN_OFFSET=0, MAX_OFFSET=60, UNIQ_KEY=C0A8001C314C5FD0D5AE9283D189000B, WAIT=true}, body=[123, 34, 100, 97, 116, 97, 34, 58, 110, 117, 108, 108, 44, 34, 100, 97, 116, 97, 98, 97, 115, 101, 34, 58, 34, 116, 49, 34, 44, 34, 101, 115, 34, 58, 49, 53, 52, 51, 52, 53, 57, 55, 49, 50, 48, 48, 48, 44, 34, 105, 100, 34, 58, 54, 44, 34, 105, 115, 68, 100, 108, 34, 58, 102, 97, 108, 115, 101, 44, 34, 109, 121, 115, 113, 108, 84, 121, 112, 101, 34, 58, 110, 117, 108, 108, 44, 34, 111, 108, 100, 34, 58, 110, 117, 108, 108, 44, 34, 115, 113, 108, 34, 58, 34, 99, 114, 101, 97, 116, 101, 32, 100, 97, 116, 97, 98, 97, 115, 101, 32, 116, 49, 34, 44, 34, 115, 113, 108, 84, 121, 112, 101, 34, 58, 110, 117, 108, 108, 44, 34, 116, 97, 98, 108, 101, 34, 58, 34, 34, 44, 34, 116, 115, 34, 58, 49, 53, 52, 51, 52, 53, 57, 55, 49, 50, 51, 57, 50, 44, 34, 116, 121, 112, 101, 34, 58, 34, 81, 85, 69, 82, 89, 34, 125], transactionId='null'}]]
2018-11-29 10:48:32.405 ERROR 23489 --- [pool-9-thread-1] c.a.o.c.a.l.l.CanalAdapterRocketMQWorker : Outer adapter write failed

配置文件：
``` yml
server:
  port: 8081
logging:
  level:
    org.springframework: WARN
    com.alibaba.otter.canal.client.adapter.hbase: DEBUG
    com.alibaba.otter.canal.client.adapter.es: DEBUG
    com.alibaba.otter.canal.client.adapter.rdb: DEBUG
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  zookeeperHosts: 127.0.0.1:2181
  mqServers: 127.0.0.1:9876
  flatMessage: true
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  mode: rocketMQ
  canalAdapters:
  - instance: example
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: rdb
        key: mysql
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver
          jdbc.url: jdbc:mysql://127.0.0.1:3306
          jdbc.username: root
          jdbc.password: ----------
          threads: 5
          commitSize: 5000
```
