### ISSUE TITLE
Outer adapter write failed

### ISSUE THREAD

**Issue by linyongfu2013** [alibaba/canal#1258]
在数据库里插入数据，同步ES失败，刚接触，日志提示比较简单，不明白是什么问题。
log 日志： Outer adapter write failed

配置文件：

**application.yml**

```
server:
  port: 8081
logging:
  level:
    org.springframework: WARN
    com.alibaba.otter.canal.client.adapter.hbase: DEBUG
    com.alibaba.otter.canal.client.adapter.es: DEBUG
    com.alibaba.otter.canal.client.adapter.rdb: DEBUG
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  canalServerHost: 127.0.0.1:11111
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  mode: tcp # kafka rocketMQ
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://127.0.0.1:3307/testdb?useUnicode=true
      username: root
      password: 123456
  canalAdapters:
  - instance: example # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: es
        hosts: 127.0.0.1:9300
        properties:
          cluster.name: elasticsearch_reid
```

**es**：

```
dataSourceKey: defaultDS
destination: example
esMapping:
  _index: testdb
  _type: test
  _id: id
  sql: "select id, content from test"
  commitBatch: 3000
```
