### ISSUE TITLE
RDB表映射未设置主键映射会导致更新和删除出错

### ISSUE THREAD

**Issue by dsf66zcq** [alibaba/canal#1423]
### environment

* canal version 1.1.3
* mysql version 5.6

### Issue Description
测试时发现单表同步如果未设置主键映射会导致更新和删除出错
![image](https://user-images.githubusercontent.com/29724943/51106903-2cbf3e00-1828-11e9-85b5-b25cb0855a57.png)

查看代码应该是RdbSyncService.appendCondition方法错误截断了sql导致
![image](https://user-images.githubusercontent.com/29724943/51106861-04374400-1828-11e9-9efe-1e968847c24c.png)

### Steps to reproduce
表映射文件:
```
dataSourceKey: defaultDS
destination: example
outerAdapterKey: pg
concurrent: true
dbMapping:
  database: test
  table: xdual
  targetTable: canal_test.xdual
  targetColumns:
    id: id
    x: x
```
### Expected behaviour
正常更新和删除
### Actual behaviour
更新和删除报错
