### ISSUE TITLE
1.1.2 es adapter 有个线程一直在报错，但是功能正常

### ISSUE THREAD

**Issue by JunRzz** [alibaba/canal#1431]
```
2019-01-15 14:44:32.137 ERROR 7036 --- [pool-4-thread-1] c.a.o.c.a.l.loader.CanalAdapterWorker    : Outer adapter write failed
2019-01-15 14:44:32.138 ERROR 7036 --- [pool-4-thread-1] c.a.o.c.a.l.loader.CanalAdapterWorker    : Outer adapter write failed
2019-01-15 14:45:16.690 ERROR 7036 --- [pool-4-thread-1] c.a.o.c.a.l.loader.CanalAdapterWorker    : Outer adapter write failed
```

es adapter 配置完成后，ETL和增量同步功能都没问题，但是日志里面会一直打印error，请问这是什么原因呢？

conf 如下：
```
dataSourceKey: defaultDS
destination: dev
esMapping:
  _index: device_info
  _type: _doc
  _id: _id
#  pk: id
  sql: "select a.id as _id,a.id as deviceId,a.create_at as createAt,a.device_name as deviceName,a.product_id as productId,a.sn as sn ,a.device_type as deviceType from device_info a"
# objFields:
#    _labels: array:;
  etlCondition: ""
  commitBatch: 3000
```
application.yml 如下：
```
server:
  port: 8081
logging:
  level:
    org.springframework: TRACE
    com.alibaba.otter.canal.client.adapter.hbase: DEBUG
    com.alibaba.otter.canal.client.adapter.es: DEBUG
    com.alibaba.otter.canal.client.adapter.rdb: DEBUG
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
#  canalServerHost: localhost:11111
  zookeeperHosts: 172.16.20.62:32609
#  mqServers: slave1:6667 #or rocketmq
#  flatMessage: true
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  mode: tcp # kafka rocketMQ
  srcDataSources:
   defaultDS:
     url: jdbc:mysql://172.16.20.63:3306/ioternet?useUnicode=true
     username: root
     password: root
  canalAdapters:
  - instance: dev
    groups:
    - groupId: g1
      outerAdapters:
      - name: es
        hosts: 172.16.20.64:39300
        properties:
          cluster.name: elasticsearch
#      - name: rdb
#        key: oracle1
#        properties:
#          jdbc.driverClassName: oracle.jdbc.OracleDriver
#          jdbc.url: jdbc:oracle:thin:@localhost:49161:XE
#          jdbc.username: mytest
#          jdbc.password: m121212
#      - name: rdb
#        key: postgres1
#        properties:
#          jdbc.driverClassName: org.postgresql.Driver
#          jdbc.url: jdbc:postgresql://localhost:5432/postgres
#          jdbc.username: postgres
#          jdbc.password: 121212
#          threads: 1
#          commitSize: 3000
#      - name: hbase
#        properties:
#          hbase.zookeeper.quorum: 127.0.0.1
#          hbase.zookeeper.property.clientPort: 2181
#          zookeeper.znode.parent: /hbase
#      - name: es
#        hosts: 127.0.0.1:9300
#        properties:
#          cluster.name: elasticsearch
```
