### ISSUE TITLE
es 同步问题

### ISSUE THREAD

**Issue by linyongfu2013** [alibaba/canal#1514]
### environment

* canal version  1.1.3
* mysql version  5.7.20
* es version  6.5.0

### Issue Description
修改mysql 行记录数据，adapter 有监测到数据变更，但并没有同步到es，控制台打印如下日志：

```
2019-02-15 16:58:38.947  INFO 51934 --- [pool-3-thread-1] c.a.o.c.c.a.logger.LoggerAdapterExample  : DML: {"data":null,"database":"inner3","destination":"example","es":1550221118000,"isDdl":null,"old":null,"pkNames":[],"sql":"/* ApplicationName=DataGrip 2017.2.2 */ UPDATE `inner3`.`tb_space` t SET t.`space_name` = '哈哈大笑1234' WHERE t.`id` = 1008612772","table":"tb_space","ts":1550221118947,"type":"UPDATE"}
2019-02-15 16:58:38.948 DEBUG 51934 --- [pool-3-thread-1] c.a.o.c.c.a.es.service.ESSyncService     : DML: {"data":null,"database":"inner3","destination":"example","es":1550221118000,"isDdl":null,"old":null,"pkNames":[],"sql":"/* ApplicationName=DataGrip 2017.2.2 */ UPDATE `inner3`.`tb_space` t SET t.`space_name` = '哈哈大笑1234' WHERE t.`id` = 1008612772","table":"tb_space","ts":1550221118948,"type":"UPDATE"}
```

具体配置文件：
application.yml
```
server:
  port: 8081
logging:
  level:
    org.springframework: INFO
    com.alibaba.otter.canal.client.adapter.hbase: DEBUG
    com.alibaba.otter.canal.client.adapter.es: DEBUG
    com.alibaba.otter.canal.client.adapter.rdb: DEBUG
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  canalServerHost: 127.0.0.1:11111
  batchSize: 1
  syncBatchSize: 1
  retries: 0
  timeout:
  accessKey:
  secretKey:
  mode: tcp # kafka rocketMQ
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://127.0.0.1:3307/inner3?useUnicode=true
      username: root
      password: 123456
  canalAdapters:
  - instance: example
    groups:
    - groupId: adapter1
      outerAdapters:
      - name: logger
      - name: es
        hosts: 127.0.0.1:9300
        properties:
          cluster.name: elasticsearch_reid
```

inner_space.yml
```
dataSourceKey: defaultDS
destination: example
esMapping:
  _index: inner_space
  _type: space
  _id: _id
#  pk: id
  sql: "select id as _id, space_name as spaceName from tb_space"
#  objFields:
#    _labels: array:;
  etlCondition: "where id >= '{0}'"
  commitBatch: 10
```
