### ISSUE TITLE
canal-adapter 1.1.3版本es同步出现 Outer adapter sync failed!  Error sync but ACK!是什么意思？

### ISSUE THREAD

**Issue by wajika** [alibaba/canal#1624]
### environment

* canal version 1.1.3
* mysql version 5.6.13

### Issue Description
能不能改下代码，明确下错误的实际意思？
我创建了es 的mapping，但是还是会提示 Outer adapter sync failed!  Error sync but ACK!

**Comment by wajika** [comment]
es的配置参数
dataSourceKey: defaultDS
destination: xxx
esMapping:
  _index: mytest
  _type: _doc
  _id: _id
  pk: forderid
  sql: "SELECT forderid,fpusername FROM t_childorder"
#  objFields:
#
#    _labels: array:;
  etlCondition: "where a.c_time>='{0}'"
  commitBatch: 3000

**Comment by rewerma** [comment]
日志应该有详细错误输出的，我看你配置里有：
```
objFileds：
  _labels： array:;
```
然而你的sql里面没有_labels字段，多看wiki先弄清楚每个属性的含义再配置

**Comment by wajika** [comment]
> 日志应该有详细错误输出的，我看你配置里有：
> 
> ```
> objFileds：
>   _labels： array:;
> ```
> 然而你的sql里面没有_labels字段，多看wiki先弄清楚每个属性的含义再配置

#  objFields:
#
#    _labels: array:;
格式显示不正常，这里是注释的状态。我看了好几遍wiki，就那一行字，也没有说的很清楚。

日志中的错误信息只有这个

2019-03-22 23:36:14.778 ERROR 7153 --- [       Thread-4] c.a.o.c.a.l.l.CanalAdapterKafkaWorker    : java.lang.RuntimeException: Outer adapter sync failed!  Error sync but ACK!
2019-03-22 23:36:14.780 ERROR 7153 --- [pool-3-thread-1] c.a.o.c.a.l.l.CanalAdapterKafkaWorker    : null

java.lang.NullPointerException: null
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:143) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:135) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:197) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$4(AbstractCanalAdapterWorker.java:105) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_131]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$5(AbstractCanalAdapterWorker.java:102) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]

**Comment by rewerma** [comment]
报npe了，你用的最新的代码吗？把配置贴出来看一下

**Comment by wajika** [comment]
server启动后 都还好。就是adapter的问题比较多
```
[root@localhost es]# cat /opt/adapter_kafka/conf/es/estest.yml 
dataSourceKey: defaultDS
destination: xxx
esMapping:
  _index: mytest
  _type: _doc
  _id: _id
  pk: forderid
  sql: "SELECT forderid,fpusername FROM t_groupon_childorder"
  etlCondition: "where a.c_time>='{0}'"
  commitBatch: 3000
```

```
[root@localhost conf]# cat application.yml 
server:
  port: 8081
logging:
  level:
    org.springframework: WARN
    com.alibaba.otter.canal.client.adapter.hbase: DEBUG
    com.alibaba.otter.canal.client.adapter.es: DEBUG
    com.alibaba.otter.canal.client.adapter.rdb: DEBUG
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
# canalServerHost: 127.0.0.1:11111
  zookeeperHosts: 192.168.10.172:2181
  mqServers: 192.168.10.172:9092
  flatMessage: true
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  #timeout:
  #accessKey:
  #secretKey:
  mode: kafka
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://192.168.10.172:25022/xxx?useUnicode=true
      username: canal
      password: canal
  canalAdapters:
  - instance: kafka
    groups:
    - groupId: g1
      outerAdapters:
      - name: es
        hosts: 192.168.10.229:9300
        properties:
          cluster.name: elasticsearch
```

**Comment by rewerma** [comment]
pk不是这样用的。。。
如果你这里的forderid是主键的话，正确的写法应该是这样：
```
dataSourceKey: defaultDS
destination: xxx
esMapping:
  _index: mytest
  _type: _doc
  _id: _id
  sql: "SELECT forderid as _id, fpusername FROM t_groupon_childorder"
  commitBatch: 3000
```
请按照wiki的格式写

**Comment by wajika** [comment]
> pk不是这样用的。。。
> 如果你这里的forderid是主键的话，正确的写法应该是这样：
> 
> ```
> dataSourceKey: defaultDS
> destination: xxx
> esMapping:
>   _index: mytest
>   _type: _doc
>   _id: _id
>   sql: "SELECT forderid as _id, fpusername FROM t_groupon_childorder"
>   commitBatch: 3000
> ```
> 请按照wiki的格式写

我原来就是那样写的，试来试去都不行
我的表主键是rowid，我改为这样，也是报错（Outer adapter sync failed!  Error sync but ACK!）
```
[root@localhost conf]# cat es/estest.yml 
dataSourceKey: defaultDS
destination: wenzhou
esMapping:
  _index: mytest
  _type: _doc
  _id: _id
#  pk: forderid
  sql: "SELECT rowid as _id,fpusername FROM t_groupon_childorder"
  etlCondition: "where a.c_time>='{0}'"
  commitBatch: 3000
```
搞不懂到底是什么错误。
wiki 参数配置内容也不太详细
我感觉是写入es的问题，但是adapter启动后没有给我更多的错误信息

**Comment by wajika** [comment]
@agapple @rewerma  麻烦解决一下把

**Comment by purevirtual** [comment]
> @agapple @rewerma 麻烦解决一下把
我也碰到了类似的问题 不过我这边是总是显示

```
2019-04-11 18:04:04.829 [pool-4-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{VAS2f6iMTR2ha0H38p-L5w}{x.ethercap.com}{192.168.1.3:9300}, {#transport#-2}{-CEQef0JQ3KNcet7Jggubw}{x.ethercap.com}{192.168.1.3:9200}]]
2019-04-11 18:04:04.830 [Thread-9] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - Outer adapter sync failed!  Error sync but ACK!
```

我的配置如下
```
canalAdapters:
- instance: example # canal instance Name or mq topic name
  groups:
  - groupId: g1
    outerAdapters:
    - name: es
      hosts: x.ethercap.com:9300,x.ethercap.com:9200
      properties:
        cluster.name: elasticsearch

```
