### ISSUE TITLE
canal-adapter-es配置文件问题

### ISSUE THREAD

**Issue by purevirtual** [alibaba/canal#1687]
## Question
canal 版本1.1.3
想要同步rds到es里 logger已经ok了 仔细读完了https://github.com/alibaba/canal/wiki/Sync-ES
发现两个问题：

- 1 如果es配置了用户名和密码 该如何配置呢？username&password? 示例里面没有
- 2 加载的时候报找不到 defaultDS，但是配置文件里明明有 而且logger启动的时候可以成功获取
```
2019-04-10 18:24:18.791 [main] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: es failed
java.lang.RuntimeException: java.lang.RuntimeException: Not found the schema of jdbc-url: defaultDS
```

## 配置文件如下
```
server:
   port: 20811
 spring:
   jackson:
     date-format: yyyy-MM-dd HH:mm:ss
     time-zone: GMT+8
     default-property-inclusion: non_null

 canal.conf:
   mode: tcp # kafka rocketMQ
   canalServerHost: 127.0.0.1:11111
   batchSize: 500
   syncBatchSize: 1000
   retries: 0
   timeout:
   accessKey:
   secretKey:
   srcDataSources:
     defaultDS:
       url: jdbc:mysql://rm-**.mysql.rds.aliyuncs.com:3306?useUnicode=true
       username: ****
       password: ****
   canalAdapters:
   - instance: example # canal instance Name or mq topic name
     groups:
     - groupId: g1
       outerAdapters:
         - name: es
          hosts: newdev.ethercap.com:9300
          properties:
            cluster.name: elasticsearch
```
