### ISSUE TITLE
Sync HBase，Adapter启动日志无报错，logger模式可正常打印DML，但hbase模式无法同步数据

### ISSUE THREAD

**Issue by jinguangyu** [alibaba/canal#1779]
**environment**

- canal version 1.1.3

- mysql version 5.7

- hbase version 2.0.2

**Issue Description**

_application.yml内容_

```
server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp # kafka rocketMQ
#  canalServerHost: 172.25.159.17:11111
  zookeeperHosts: master1.spark.data-hz.com:2181
#  mqServers: 127.0.0.1:9092 #or rocketmq
#  flatMessage: true
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://**************.mysql.rds.aliyuncs.com:3306/metrics?useUnicode=true
      username: ***********
      password: ***********
  canalAdapters:
  - instance: testbinlog # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
#      - name: logger
    - name: hbase
      properties:
        hbase.zookeeper.quorum: master1.spark.data-hz.com,master2.spark.data-hz.com
        hbase.zookeeper.property.clientPort: 2181
        zookeeper.znode.parent: /hbase-unsecure
```
_mytest_person2.yml文件内容_
```
dataSourceKey: defaultDS
destination: testbinlog
groupId: g1
hbaseMapping:
  mode: STRING  #NATIVE   #PHOENIX
  database: metrics  # 数据库名
  table: test_bin_log     # 数据库表名
  hbaseTable: METRICS:TESTBINLOG   # HBase表名
  family: CF  # 默认统一Family名称
  uppercaseQualifier: true  # 字段名转大写, 默认为true
  commitBatch: 3000 # 批量提交的大小
  #rowKey: id,type  # 复合字段rowKey不能和columns中的rowKey重复
  columns:
    # 数据库字段:HBase对应字段
    id: ROWKEY
    name: CF:NAME
```
