### ISSUE TITLE
fastsql.sql.parser.ParserException

### ISSUE THREAD

**Issue by wajika** [alibaba/canal#1842]
### 我的es配置
```

dataSourceKey: defaultDS
destination: tcpip
groupId: g1
esMapping:
  _index: ceshi_mysql
  _type: _doc
#  _id: _id
  upsert: true
  pk: id
  sql: "SELECT a.rowid AS id,a.fid AS fid,a.fmaxlength AS fmaxlength,b.fkeyarea AS fkeyarea,b.flastbrowsarea AS flastbrowsarea,
b.fcreatetime AS fcreatetime FROM t_user_device_parameters a 
LEFT JOIN t_user_historyarea b ON a.fuserid=b.fuserid"
#  etlCondition: "where a.c_time>='{0}'"
  commitBatch: 3000
```
SQL语句在数据库中是可以直接运行的

### adapter的日志
https://pastebin.com/raw/U9JFHY2u

### es的日志
https://pastebin.com/raw/DQCjzFa0
里面报错java.lang.RuntimeException: com.alibaba.fastsql.sql.parser.ParserException
