### ISSUE TITLE
canal adapter 同步时使用 concat(字段1, 字段2)  作为_id，能同步新增，但不能同步删除

### ISSUE THREAD

**Issue by JustPlay1994** [alibaba/canal#1923]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
1.1.3
* mysql version
5.7
* elasticsearch version
6.5.4
### Issue Description
canal adapter 同步时使用 concat(字段1, 字段2)  作为_id，能同步新增，但不能同步删除

### Steps to reproduce
配置如下：
```
dataSourceKey: defaultDS
destination: example
groupId: g1
esMapping:
  _index: test
  _type: _doc
  _id: _id
  upsert: true
  sql: "select concat(video_id,label_id) _id, video_id, label_id from test"
  etlCondition:
  commitBatch: 3000
```
### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
