### ISSUE TITLE
canal-adapter在同步MySQL数据到ES的时候，delete的时候，如果ES的id不采用MySQL的字段，会update，而不是delete

### ISSUE THREAD

**Issue by okamiv** [alibaba/canal#1961]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
* mysql version

### Issue Description
canal-adapter的配置如下， es的id采用自生成的策略
```
dataSourceKey: defaultDS
destination: example
groupId: g1
esMapping:
  _index: index
  _type: user
  upsert: false
  pk: c_id
  sql: "select a.id as c_id, a.name as name  from user a"
  commitBatch: 3000
```
mysql的数据delete的时候， 会将原来的数据的字段update为null，但是不会delete掉
```
   public void delete(ESMapping mapping, Object pkVal, Map<String, Object> esFieldData) {
        if (mapping.get_id() != null) {
            getBulk().add(transportClient.prepareDelete(mapping.get_index(), mapping.get_type(), pkVal.toString()));
            commitBulk();
        } else {
            SearchResponse response = transportClient.prepareSearch(mapping.get_index())
                .setTypes(mapping.get_type())
                .setQuery(QueryBuilders.termQuery(mapping.getPk(), pkVal))
                .setSize(10000)
                .get();
            for (SearchHit hit : response.getHits()) {
               // 这里执行的是update，而不是delete
                getBulk().add(transportClient.prepareUpdate(mapping.get_index(), mapping.get_type(), hit.getId()).setDoc(esFieldData));
                commitBulk();
            }
        }

    }
```

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
