### ISSUE TITLE
如果修改主表字段，从表刚好有同名字段，ES中会一并修改从表对应的字段

### ISSUE THREAD

**Issue by xmuyoucai** [alibaba/canal#2023]
**测试表结构**
```
CREATE TABLE `t_user` (
  `id` int(11) NOT NULL DEFAULT '0',
  `name` varchar(50) DEFAULT NULL,
  `age` int(2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
```
CREATE TABLE `t_clz` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11613 DEFAULT CHARSET=utf8mb4;
```
```
CREATE TABLE `t_score` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `score` int(2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1002 DEFAULT CHARSET=utf8mb4;
```
**配置信息**
```
dataSourceKey: aliyunDS
destination: zyloops
groupId: g1
esMapping:
  _index: aliyun2
  _type: user
  _id: _id
  upsert: true
  sql: "select a.id as _id, a.name as name, a.age as age, b.name as clzName, c.score as score from t_user a left join t_clz b on a.id = b.user_id left join t_score c on a.id = c.user_id"
  commitBatch: 3000
```
**更新操作**
```
INSERT INTO t_user (`id`, `name`, `age`) VALUES (65, 'Jone', 18);
INSERT INTO t_clz (`user_id`, `name`) VALUES (65, '1 grade');
INSERT INTO t_score (`user_id`, `score`) VALUES (65, 50);
UPDATE t_user SET `name` = 'zyloops' WHERE id = 65;
```
**ES 结果**
```
{"_index":"aliyun2","_type":"user","_id":"65","_version":3,"found":true,"_source":{"name":"zyloops","age":18,"clzName":"zyloops","score":65}}
```
**当更新 65 这条记录的名称时，在 ES 里会同时将课程名称也改为 zyloops！！！**
