### ISSUE TITLE
docker的swarm下canal-admin无法外置，canal-server无法正常启动

### ISSUE THREAD

**Issue by kervin521** [alibaba/canal#2133]
## Question

版本: v1.1.4
```yml
version: '3.7'
services:
  canal-server:
      image: canal/canal-server:v1.1.4
      restart: always
      environment:
      - canal.admin.manager=canal-admin:8089
      - canal.admin.port=11110
      - canal.admin.user=admin
      - canal.admin.passwd=4ACFE3202A5FF5CF467898FC58AAB1D615029441
      - canal.admin.register.cluster=canal
      volumes:
      - /opt/deploy/data/canal/server:/home/admin/canal-server/conf
      - /etc/localtime:/etc/localtime
      ports:
      - 11111:11111
      deploy:
         replicas: 1
   canal-admin:
      image: canal/canal-admin:v1.1.4
      restart: always
      environment:
      - server.max-http-header-size=100000
      - spring.datasource.address=172.21.32.111:3306
      - spring.datasource.database=canal_manager
      - canal.adminUser=admin
      - canal.adminPasswd=admin
      volumes:
      - /opt/deploy/data/canal/admin:/home/admin/canal-admin/conf
      - /etc/localtime:/etc/localtime
      ports:
      - 8089:8089
      - 11110:11110
      deploy:
         replicas: 1
```
