### ISSUE TITLE
Canal支持mysql的分库分表吗？

### ISSUE THREAD

**Issue by JunjianS** [alibaba/canal#2208]
## Question

现在业务库的mysql是分库分表的，canal支持吗？

**Comment by bsed** [comment]
我用的笨方法 感觉你可以试试 这种 
![image](https://user-images.githubusercontent.com/10845087/65405620-3ebd9b80-de0f-11e9-8bdf-a7fbf1b817d7.png)
```
server:
  port: 8081
logging:
  level:
    org.springframework: WARN
    com.alibaba.otter.canal.client.adapter.hbase: DEBUG
    com.alibaba.otter.canal.client.adapter.es: DEBUG
    com.alibaba.otter.canal.client.adapter.rdb: DEBUG
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  canalServerHost: 127.0.0.1:11111
#  zookeeperHosts: slave1:2181
  mqServers: 10.200.200.6:9876 #slave1:6667 #or rocketmq
  flatMessage: true
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  mode: rocketMQ # kafka rocketMQ
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://10.200.200.8:3306/xxx?useUnicode=true
      username: xxx
      password: xxx
    defaultDS1:
      url: jdbc:mysql://10.200.200.8:3306/xxxx?useUnicode=true
      username: xxx
      password: xxx
  canalAdapters:
  - instance: example # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
#      - name: logger
#      - name: rdb
#        key: oracle1
#        properties:
#          jdbc.driverClassName: oracle.jdbc.OracleDriver
#          jdbc.url: jdbc:oracle:thin:@localhost:49161:XE
#          jdbc.username: mytest
#          jdbc.password: m121212
#      - name: rdb
#        key: postgres1
#        properties:
#          jdbc.driverClassName: org.postgresql.Driver
#          jdbc.url: jdbc:postgresql://localhost:5432/postgres
#          jdbc.username: postgres
#          jdbc.password: 121212
#          threads: 1
#          commitSize: 3000
#      - name: hbase
#        properties:
#          hbase.zookeeper.quorum: 127.0.0.1
#          hbase.zookeeper.property.clientPort: 2181
#          zookeeper.znode.parent: /hbase
      - name: es
        hosts: 10.200.200.6:9300
        properties:
          cluster.name: qa-application
```
