### ISSUE TITLE
求助：canal 1.1.5 同步mysql 到 es7.1.0

### ISSUE THREAD

**Issue by maiganne** [alibaba/canal#2726]
## 上下文
mysql 两张表：
```
user 表: id，name
tag 表 :id，user_id，tag_name
```

es 索引 user mapping
```
{
  "settings": {
    "number_of_shards": 5,
    "number_of_replicas": 1
  },
  "mappings": {
    "properties": {
      "user_join": {
        "type": "join",
        "eager_global_ordinals": true,
        "relations": {
          "user": ["tag"]
        }
      },
      "user_name": {
        "type": "keyword"
      },
      "tag_name": {
        "type": "keyword"
      }

    }
  }
}
```

同步 映射配置
```
dataSourceKey: defaultDS
destination: example
groupId: g1
esMapping:
  _index: user
  _type: _doc
  _id: _id
  relations:
    user_join:
      name: tag
      parent: user_id
  upsert: true
#  pk: id
  sql: "SELECT a.id as _id,a.user_id,a.tag_name from tag as a "
  skips:
    - user_id
````

现在遇到的问题是:
当 es 索引 user 主分片设置为1时，同步工作正常，mysql 添加一条tag 记录，es user索引会增加一条子文档；mysql 删除一条tag 记录，es user索引会删除对应的子文档。
当es 索引 user 主分片设置为5时，同步工作不正常，mysql 添加一条tag 记录，es user索引会增加一条子文档；mysql 删除一条tag 记录，es user索引不会删除对应的子文档。
我估计是在多个分片的情况下，删除 es 文档时，没有指定 routing 导致的，那么该怎么配置呢
