### ISSUE TITLE
client adapter rdb 同步到下游TiDB后日期发生变化。

### ISSUE THREAD

**Issue by qinggniq** [alibaba/canal#2868]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
master分支源码编译，最新commit为 9f6021cf36f78cc8ac853dcf37a1769f359b868b。
* tidb version
上游：v4.00
下游：v4.00
* kafka version
stable 2.5.0
* client adapter 配置：
```yml
server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: kafka
  flatMessage: false
  zookeeperHosts:
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  consumerProperties:
    kafka.bootstrap.servers: 127.0.0.1:9092
    kafka.enable.auto.commit: false
    kafka.auto.commit.interval.ms: 1000
    kafka.auto.offset.reset: latest
    kafka.request.timeout.ms: 40000
    kafka.session.timeout.ms: 30000
    kafka.isolation.level: read_committed
    kafka.max.poll.records: 1000
  canalAdapters:
  - instance: canal-test-4 # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: rdb
        key: mysql1
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver
          jdbc.url: jdbc:mysql://127.0.0.1:3306/row_format
          jdbc.username: root
          jdbc.password:
```
* 表映射
```yml
## Mirror schema synchronize config
dataSourceKey: defaultDS
destination: canal-test-4
groupId: g1
outerAdapterKey: mysql1
#concurrent: true
dbMapping:
  mirrorDb: true
  database: row_format
```
* 插入的sql数据
```sql
use `row_format`;

SET GLOBAL tidb_row_format_version = 2;

CREATE TABLE multi_data_type
(
    id          INT AUTO_INCREMENT,
    t_boolean   BOOLEAN,
    t_bigint    BIGINT,
    t_double    DOUBLE,
    t_decimal   DECIMAL(38, 19),
    t_bit       BIT(64),
    t_date      DATE,
    t_datetime  DATETIME,
    t_timestamp TIMESTAMP NULL,
    t_time      TIME,
    t_year      YEAR,
    t_char      CHAR,
    t_varchar   VARCHAR(10),
    t_blob      BLOB,
    t_text      TEXT,
    t_enum      ENUM ('enum1', 'enum2', 'enum3'),
    t_set       SET ('a', 'b', 'c'),
    t_json      JSON,
    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  COLLATE = utf8_bin;

INSERT INTO multi_data_type( t_boolean, t_bigint, t_double, t_decimal, t_bit
                           , t_date, t_datetime, t_timestamp, t_time, t_year
                           , t_char, t_varchar, t_blob, t_text, t_enum
                           , t_set, t_json)
VALUES ( true, 9223372036854775807, 123.123, 123456789012.123456789012, b'1000001'
       , '1000-01-01', '9999-12-31 23:59:59', '19731230153000', '23:59:59', 1970
       , '测', '测试', 'blob', '测试text', 'enum2'
       , 'a,b', NULL);
...
```

### Issue Description
上游数据库插入列类型为Date类型的数据（也就是t_date列）"1000-01-01"，同步到下游后改列的数据变为"0999-12-27"。

### Expected behaviour
下游的数据库date列值也是“1000-01-01”。
### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
