### ISSUE TITLE
canal-adapter启动失败，无日志输出

### ISSUE THREAD

**Issue by ChunKai93** [alibaba/canal#2911]
发行版：ubuntu20.04
jdk版本：
```
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
```
canal-adapter：canal.adapter-1.1.3.tar.gz
目录结构：
```
chau@chau-desktop:~/canal-adapter$ ls
bin  conf  lib  logs  plugin
```
启动./bin/startup.sh

cd to /home/chau/canal-adapter/bin for workaround relative path
CLASSPATH :/home/chau/canal-adapter/bin/../conf:/home/chau/canal-adapter/bin/../lib/zookeeper-3.4.5.jar:/home/chau/canal-adapter/bin/../lib/zkclient-0.10.jar:/home/chau/canal-adapter/bin/../lib/validation-api-2.0.1.Final.jar:/home/chau/canal-adapter/bin/../lib/tomcat-embed-websocket-8.5.29.jar:/home/chau/canal-adapter/bin/../lib/tomcat-embed-el-8.5.29.jar:/home/chau/canal-adapter/bin/../lib/tomcat-embed-core-8.5.29.jar:/home/chau/canal-adapter/bin/../lib/spring-webmvc-5.0.5.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-web-5.0.5.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-tx-5.0.5.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-security-crypto-5.0.4.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-orm-5.0.5.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-jdbc-5.0.5.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-jcl-5.0.5.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-expression-5.0.5.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-core-5.0.5.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-context-5.0.5.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-cloud-context-2.0.0.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-boot-starter-web-2.0.1.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-boot-starter-tomcat-2.0.1.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-boot-starter-logging-2.0.1.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-boot-starter-json-2.0.1.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-boot-starter-2.0.1.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-boot-autoconfigure-2.0.1.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-boot-2.0.1.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-beans-5.0.5.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/spring-aop-5.0.5.RELEASE.jar:/home/chau/canal-adapter/bin/../lib/snappy-java-1.1.7.1.jar:/home/chau/canal-adapter/bin/../lib/snakeyaml-1.19.jar:/home/chau/canal-adapter/bin/../lib/slf4j-api-1.7.25.jar:/home/chau/canal-adapter/bin/../lib/rocketmq-remoting-4.3.0.jar:/home/chau/canal-adapter/bin/../lib/rocketmq-logging-4.3.0.jar:/home/chau/canal-adapter/bin/../lib/rocketmq-common-4.3.0.jar:/home/chau/canal-adapter/bin/../lib/rocketmq-client-4.3.0.jar:/home/chau/canal-adapter/bin/../lib/protobuf-java-3.6.1.jar:/home/chau/canal-adapter/bin/../lib/postgresql-42.1.4.jar:/home/chau/canal-adapter/bin/../lib/ojdbc6-11.2.0.3.jar:/home/chau/canal-adapter/bin/../lib/netty-tcnative-boringssl-static-1.1.33.Fork26.jar:/home/chau/canal-adapter/bin/../lib/netty-all-4.1.23.Final.jar:/home/chau/canal-adapter/bin/../lib/netty-3.2.2.Final.jar:/home/chau/canal-adapter/bin/../lib/mysql-connector-java-5.1.40.jar:/home/chau/canal-adapter/bin/../lib/mssql-jdbc-7.0.0.jre8.jar:/home/chau/canal-adapter/bin/../lib/lz4-java-1.4.1.jar:/home/chau/canal-adapter/bin/../lib/logback-core-1.2.3.jar:/home/chau/canal-adapter/bin/../lib/logback-classic-1.2.3.jar:/home/chau/canal-adapter/bin/../lib/log4j-to-slf4j-2.10.0.jar:/home/chau/canal-adapter/bin/../lib/log4j-api-2.10.0.jar:/home/chau/canal-adapter/bin/../lib/kafka-clients-1.1.1.jar:/home/chau/canal-adapter/bin/../lib/jul-to-slf4j-1.7.25.jar:/home/chau/canal-adapter/bin/../lib/jsr305-3.0.2.jar:/home/chau/canal-adapter/bin/../lib/joda-time-2.9.9.jar:/home/chau/canal-adapter/bin/../lib/jcl-over-slf4j-1.7.25.jar:/home/chau/canal-adapter/bin/../lib/jboss-logging-3.3.2.Final.jar:/home/chau/canal-adapter/bin/../lib/javax.annotation-api-1.3.2.jar:/home/chau/canal-adapter/bin/../lib/jackson-module-parameter-names-2.9.5.jar:/home/chau/canal-adapter/bin/../lib/jackson-datatype-jsr310-2.9.5.jar:/home/chau/canal-adapter/bin/../lib/jackson-datatype-jdk8-2.9.5.jar:/home/chau/canal-adapter/bin/../lib/jackson-databind-2.9.5.jar:/home/chau/canal-adapter/bin/../lib/jackson-core-2.9.5.jar:/home/chau/canal-adapter/bin/../lib/jackson-annotations-2.9.0.jar:/home/chau/canal-adapter/bin/../lib/hibernate-validator-6.0.9.Final.jar:/home/chau/canal-adapter/bin/../lib/guava-18.0.jar:/home/chau/canal-adapter/bin/../lib/fastjson-1.2.28.jar:/home/chau/canal-adapter/bin/../lib/druid-1.1.9.jar:/home/chau/canal-adapter/bin/../lib/curator-recipes-2.10.0.jar:/home/chau/canal-adapter/bin/../lib/curator-framework-2.10.0.jar:/home/chau/canal-adapter/bin/../lib/curator-client-2.10.0.jar:/home/chau/canal-adapter/bin/../lib/commons-lang3-3.7.jar:/home/chau/canal-adapter/bin/../lib/commons-lang-2.6.jar:/home/chau/canal-adapter/bin/../lib/commons-io-2.4.jar:/home/chau/canal-adapter/bin/../lib/commons-codec-1.11.jar:/home/chau/canal-adapter/bin/../lib/client-adapter.launcher-1.1.3.jar:/home/chau/canal-adapter/bin/../lib/client-adapter.common-1.1.3.jar:/home/chau/canal-adapter/bin/../lib/classmate-1.3.4.jar:/home/chau/canal-adapter/bin/../lib/canal.protocol-1.1.3.jar:/home/chau/canal-adapter/bin/../lib/canal.common-1.1.3.jar:/home/chau/canal-adapter/bin/../lib/canal.client-1.1.3.jar:/home/chau/canal-adapter/bin/../lib/aliware-apache-rocketmq-cloud-1.0.jar:.
cd to /home/chau/canal-adapter/bin for continue

此时，logs目录下无任何日志输出。

conf/application.yml
```
server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp # kafka rocketMQ
  canalServerHost: 127.0.0.1:11111
#  zookeeperHosts: slave1:2181
#  mqServers: 127.0.0.1:9092 #or rocketmq
#  flatMessage: true
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://127.0.0.1:3310/mytest?useUnicode=true
      username: root
      password: ********
  canalAdapters:
  - instance: example # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
#      - name: rdb
#        key: mysql1
#        properties:
#          jdbc.driverClassName: com.mysql.jdbc.Driver
#          jdbc.url: jdbc:mysql://127.0.0.1:3306/mytest2?useUnicode=true
#          jdbc.username: root
#          jdbc.password: 121212
#      - name: rdb
#        key: oracle1
#        properties:
#          jdbc.driverClassName: oracle.jdbc.OracleDriver
#          jdbc.url: jdbc:oracle:thin:@localhost:49161:XE
#          jdbc.username: mytest
#          jdbc.password: m121212
#      - name: rdb
#        key: postgres1
#        properties:
#          jdbc.driverClassName: org.postgresql.Driver
#          jdbc.url: jdbc:postgresql://localhost:5432/postgres
#          jdbc.username: postgres
#          jdbc.password: 121212
#          threads: 1
#          commitSize: 3000
#      - name: hbase
#        properties:
#          hbase.zookeeper.quorum: 127.0.0.1
#          hbase.zookeeper.property.clientPort: 2181
#          zookeeper.znode.parent: /hbase
      - name: es
        hosts: 127.0.0.1:9300
        properties:
          cluster.name: elasticsearch
```
conf/es/mytest_user.yml
```
dataSourceKey: defaultDS
destination: example
groupId: g1
esMapping:
  _index: mytest_user
  _type: _doc
  _id: _id
  upsert: true
#  pk: id
  sql: "select a.id as _id, a.name, a.role_id, a.c_time from user a"
#  objFields:
#    _labels: array:;
#  etlCondition: "where a.c_time>='{0}'"
  commitBatch: 3000
```
mysql，es, canal-server均部署在docker上，均正常

GET 127.0.0.1:9200/mytest_user/_mappings
```
{
    "mytest_user": {
        "mappings": {
            "_doc": {
                "properties": {
                    "c_time": {
                        "type": "date"
                    },
                    "name": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword"
                            }
                        }
                    },
                    "role_id": {
                        "type": "long"
                    }
                }
            }
        }
    }
}
```
