### ISSUE TITLE
canal-adapter-1.1.5连接不到canal server，报授权失败错，canalserver是用canaladmin管理的

### ISSUE THREAD

**Issue by xianxin27** [alibaba/canal#2950]
## Question

2020-08-14 18:51:30.691 [Thread-4] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong when doing authentication: auth failed for user:
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:192) ~[canal.client-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:115) ~[canal.client-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterWorker.process(CanalAdapterWorker.java:88) ~[client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]

**Comment by yl-yue** [comment]
```yml
canal.conf:
  consumerProperties:
    # canal tcp consumer
    canal.tcp.server.host: 77.0.3.24:11111
    canal.tcp.batch.size: 500
    canal.tcp.username: canal
    canal.tcp.password: canal
```

**Comment by 1114619217** [comment]
遇到同样的问题，解决办法是

```
canal.conf:
  consumerProperties:
    # canal tcp consumer
    canal.tcp.server.host: 127.0.0.1:11111
    canal.tcp.zookeeper.hosts:
    canal.tcp.batch.size: 500
    canal.tcp.username: admin
    canal.tcp.password: 123456
```

这里的密码是canal-admin的登录密码
