### ISSUE TITLE
使用canal-adapter进行第一次全量初始化

### ISSUE THREAD

**Issue by Viking1726** [alibaba/canal#3196]
## Why you need it?

在使用canal-adapter进行第一次全量初始化时，数据库最大连接数据设置太少，希望做成可动态配置的。
当sql跑到 “limit  4800000，1000时”，sql会超时，maxActive又只有3，会有很多数据处理失败。
现在我手动修改了这个值，替换了class。

<img width="1030" alt="WeChataf8029afc9cc70a0af8d742dd1c73859" src="https://user-images.githubusercontent.com/30591576/100062876-47728d00-2e6b-11eb-912f-d1272eb23f1d.png">

**Comment by liuxuzxx** [comment]
这个对于limit的操作，我们是这么处理的，我们有的单表(按天分表)数据达到了3000w，这个时候，我们在全同步mysql的数据到es的时候，确实遇到后面翻页很慢的问题，我们是增加了
```
dataSourceKey: defaultDS
destination: example
groupId: g1
esMapping:
  _index: gsms_short_link_batch
  _id: _id
  sql: "自己的SQL语句"
  etlCondition: "where id>={} and id<={}"//增加id限制，使用索引来定位，增加翻页速度
  commitBatch: 1500
```
预先估计这个表的最大id，然后按照id批次进行分割，超过10000，canal-adapter就能多线程插入，如果作者的表没有这种自增的有规律的索引字段，忽略我的回答！
