### ISSUE TITLE
canal.adapter 高可用部署报错

### ISSUE THREAD

**Issue by zlt2000** [alibaba/canal#3277]
### environment
* canal version：canal.adapter-1.1.5-SNAPSHOT
* apache-zookeeper-3.6.2
* mysql version：5.7

### Issue Description
canal.adapter配置zookeeper地址后启动报错：com.alibaba.otter.canal.common.zookeeper.ZkClientx.create(Ljava/lang/String;Ljava/lang/Object;Lorg/apache/zookeeper/CreateMode;)Ljava/lang/String;" the class loader (instance of com/alibaba/otter/canal/connector/core/spi/URLClassExtensionLoader) of the current class, com/alibaba/otter/canal/client/impl/running/ClientRunningMonitor, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/I0Itec/zkclient/ZkClient, have different Class objects for the type org/apache/zookeeper/CreateMode used in the signature

详细错误日志如下：
[canal-adapter-error.txt](https://github.com/alibaba/canal/files/5744705/canal-adapter-error.txt)

&nbsp;

canal.adapter的配置如下：
```
canal.conf:
  mode: tcp
  flatMessage: true
  zookeeperHosts:
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  consumerProperties:
    # canal tcp consumer
    canal.tcp.server.host: 
    canal.tcp.zookeeper.hosts: 192.168.28.130:2181
    canal.tcp.batch.size: 500
    canal.tcp.username:
    canal.tcp.password:
```
