### ISSUE TITLE
Bit type data synchronization inconsistency

### ISSUE THREAD

**Issue by hi-rustin** [alibaba/canal#3998]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

Use this docker-compose file.

```yaml
version: "3"

networks:
  canal-test:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    networks:
      - canal-test
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: docker.io/bitnami/kafka:2
    networks:
      - canal-test
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper

  kafka-consumer:
    image: docker.io/bitnami/kafka:2
    networks:
      - canal-test
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - kafka
    command: kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic example --from-beginning --property print.partition=true

  mysql-upstream:
    image: mysql:5.7
    platform: linux/amd64
    networks:
      - canal-test
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_PASSWORD: ''
    command: --log-bin=mysql-bin --port=3306 --bind-address=0.0.0.0 --binlog-format=ROW --server-id=1 --gtid_mode=ON --enforce-gtid-consistency=true

  mysql-downstream:
    image: mysql:5.7
    platform: linux/amd64
    networks:
      - canal-test
    ports:
      - "4000:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_PASSWORD: ''
    command: --log-bin=mysql-bin --port=3306 --bind-address=0.0.0.0 --binlog-format=ROW --server-id=1 --gtid_mode=ON --enforce-gtid-consistency=true

  canal:
    image: canal/canal-server
    networks:
      - canal-test
    environment:
      canal.instance.master.address: mysql-upstream:3306
      canal.instance.dbUsername: root
      canal.instance.dbPassword: ''
      canal.mq.topic: example
      canal.serverMode: kafka
      canal.mq.servers: kafka:9092
      canal.mq.flatMessage: true
    depends_on:
      - kafka
      - mysql-upstream
      - kafka-consumer

  canal-adapter:
    # Build from https://github.com/pingcap/tiflow/tree/master/scripts/canal/docker.
    image: rustinliu/ticdc-canal-json-adapter:latest
    networks:
      - canal-test
    environment:
      KAFKA_SERVER: kafka:9092
      ZOOKEEPER_SERVER: zookeeper:2181
      # This is actually the name of the topic.
      DB_NAME: example
      DOWNSTREAM_DB_HOST: mysql-downstream
      DOWNSTREAM_DB_PORT: 3306
      USE_FLAT_MESSAGE: true
    depends_on:
      - zookeeper
      - kafka
      - mysql-downstream

```
rustinliu/ticdc-canal-json-adapter：
```shell
#!/bin/sh

# This script file uses environment variable to create config of canal adapter. The format of config file `application.yml`
# is only suitable for canal adapter release version v1.1.5-alpha-2, if you want build from latest master branch, please rewrite the
# config file from canal/client-adapter/launcher/src/main/bin/conf/application.yml

KAFKA_SERVER=${KAFKA_SERVER:-localhost:9092}
ZOOKEEPER_SERVER=${ZOOKEEPER_SERVER:-localhost:2181}
DB_NAME=${DB_NAME:-testdb}
DOWNSTREAM_DB_HOST=${DOWNSTREAM_DB_HOST:-localhost}
DOWNSTREAM_DB_PORT=${DOWNSTREAM_DB_PORT:-4000}
echo "zookeeper server ${ZOOKEEPER_SERVER}"
echo "kafka server ${KAFKA_SERVER}"
echo "db name ${DB_NAME}"
echo "downstream db host ${DOWNSTREAM_DB_HOST}"
echo "downstream db port ${DOWNSTREAM_DB_PORT}"
echo "use flatMessage: ${USE_FLAT_MESSAGE}"

echo "Verifying downstream TiDB is started..."
i=0
while ! mysql -uroot -h${DOWNSTREAM_DB_HOST} -P${DOWNSTREAM_DB_PORT} --default-character-set utf8mb4 -e 'create database example;'; do
	i=$((i + 1))
	if [ "$i" -gt 20 ]; then
		echo 'Connection to downstream TiDB failed'
		break
	fi
	sleep 5
done

WORK_DIR=$(pwd)
cat - >"${WORK_DIR}/conf/application.yml" <<EOF
server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: kafka # tcp rocketMQ rabbitMQ
  flatMessage: ${USE_FLAT_MESSAGE}
  zookeeperHosts:
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  consumerProperties:
    # kafka consumer
    kafka.bootstrap.servers: ${KAFKA_SERVER}
    kafka.enable.auto.commit: false
    kafka.auto.commit.interval.ms: 1000
    kafka.auto.offset.reset: latest
    kafka.request.timeout.ms: 40000
    kafka.session.timeout.ms: 30000
    kafka.isolation.level: read_committed
    kafka.max.poll.records: 1000
  canalAdapters:
  - instance: ${DB_NAME} # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: rdb
        key: mysql1
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver
          jdbc.url: jdbc:mysql://${DOWNSTREAM_DB_HOST}:${DOWNSTREAM_DB_PORT}/${DB_NAME}
          jdbc.username: root
          jdbc.password:
EOF

cat - >"$WORK_DIR/conf/rdb/mytest_user.yml" <<EOF
# Mirror schema synchronize config
dataSourceKey: defaultDS
destination: ${DB_NAME}
groupId: g1
outerAdapterKey: mysql1
concurrent: true
dbMapping:
  mirrorDb: true
  database: ${DB_NAME}
EOF

bash ./bin/startup.sh

while true; do
	sleep 30000
done
```
### Issue Description

When we execute the following sql:

```sql
USE `example`;

CREATE TABLE multi_data_type
(
    id                   INT AUTO_INCREMENT,
    t_tinyint            TINYINT,
    t_tinyint_unsigned   TINYINT UNSIGNED,
    t_smallint           SMALLINT,
    t_smallint_unsigned  SMALLINT UNSIGNED,
    t_mediumint          MEDIUMINT,
    t_mediumint_unsigned MEDIUMINT UNSIGNED,
    t_int                INT,
    t_int_unsigned       INT UNSIGNED,
    t_bigint             BIGINT,
    t_bigint_unsigned    BIGINT UNSIGNED,
    t_boolean            BOOLEAN,
    t_float              FLOAT(6, 2),
    t_double             DOUBLE(6, 2),
    t_decimal            DECIMAL(38, 19),
    t_char               CHAR,
    t_varchar            VARCHAR(10),
    c_binary             binary(16),
    c_varbinary          varbinary(16),
    t_tinytext           TINYTEXT,
    t_text               TEXT,
    t_mediumtext         MEDIUMTEXT,
    t_longtext           LONGTEXT,
    t_tinyblob           TINYBLOB,
    t_blob               BLOB,
    t_mediumblob         MEDIUMBLOB,
    t_longblob           LONGBLOB,
    t_date               DATE,
    t_datetime           DATETIME,
    t_timestamp          TIMESTAMP NULL,
    t_time               TIME,
--  FIXME: Currently canal-adapter does not handle year types correctly.
--  t_year               YEAR,
    t_enum               ENUM ('enum1', 'enum2', 'enum3'),
    t_set                SET ('a', 'b', 'c'),
--  FIXME: Currently there will be data inconsistencies.
    t_bit                BIT(64),
    t_json               JSON,
    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  COLLATE = utf8_bin;

INSERT INTO multi_data_type( t_tinyint, t_tinyint_unsigned, t_smallint, t_smallint_unsigned, t_mediumint
                           , t_mediumint_unsigned, t_int, t_int_unsigned, t_bigint, t_bigint_unsigned
                           , t_boolean, t_float, t_double, t_decimal
                           , t_char, t_varchar, c_binary, c_varbinary, t_tinytext, t_text, t_mediumtext, t_longtext
                           , t_tinyblob, t_blob, t_mediumblob, t_longblob
                           , t_date, t_datetime, t_timestamp, t_time
                           , t_enum
                           , t_set,t_bit, t_json)
VALUES ( -1, 1, -129, 129, -65536, 65536, -16777216, 16777216, -2147483649, 2147483649
       , true, 123.456, 123.123, 123456789012.123456789012
       , '测', '测试', x'89504E470D0A1A0A', x'89504E470D0A1A0A', '测试tinytext', '测试text', '测试mediumtext', '测试longtext'
       , 'tinyblob', 'blob', 'mediumblob', 'longblob'
       , '1977-01-01', '9999-12-31 23:59:59', '19731230153000', '23:59:59'
       , 'enum2'
       , 'a,b', b'100101',NULL);

```

### Steps to reproduce
1. docker-compose -f ./docker-compose-canal.yaml up -d
2.  mysql --host 127.0.0.1 --port 3306 -u root -p --comments < data.sql
3. check the upstream and downstream results

### Expected behaviour
select * from multi_data_type;
The results are the same.

### Actual behaviour
upstream:
```json
[
  {
    "id": 1,
    "t_tinyint": -1,
    "t_tinyint_unsigned": 1,
    "t_smallint": -129,
    "t_smallint_unsigned": 129,
    "t_mediumint": -65536,
    "t_mediumint_unsigned": 65536,
    "t_int": -16777216,
    "t_int_unsigned": 16777216,
    "t_bigint": -2147483649,
    "t_bigint_unsigned": 2147483649,
    "t_boolean": 1,
    "t_float": 123.46,
    "t_double": 123.12,
    "t_decimal": 123456789012.1234567890120000000,
    "t_char": "测",
    "t_varchar": "测试",
    "c_binary": "0x89504E470D0A1A0A0000000000000000",
    "c_varbinary": "0x89504E470D0A1A0A",
    "t_tinytext": "测试tinytext",
    "t_text": "测试text",
    "t_mediumtext": "测试mediumtext",
    "t_longtext": "测试longtext",
    "t_tinyblob": "tinyblob",
    "t_blob": "blob",
    "t_mediumblob": "mediumblob",
    "t_longblob": "longblob",
    "t_date": "1977-01-01",
    "t_datetime": "9999-12-31 23:59:59",
    "t_timestamp": "1973-12-30 15:30:00",
    "t_time": "23:59:59",
    "t_enum": "enum2",
    "t_set": "a,b",
    "t_bit": "0000000000000000000000000000000000000000000000000000000000100101",
    "t_json": null
  }
]
```
downstream:
```json
[
  {
    "id": 1,
    "t_tinyint": -1,
    "t_tinyint_unsigned": 1,
    "t_smallint": -129,
    "t_smallint_unsigned": 129,
    "t_mediumint": -65536,
    "t_mediumint_unsigned": 65536,
    "t_int": -16777216,
    "t_int_unsigned": 16777216,
    "t_bigint": -2147483649,
    "t_bigint_unsigned": 2147483649,
    "t_boolean": 1,
    "t_float": 123.46,
    "t_double": 123.12,
    "t_decimal": 123456789012.1234567890120000000,
    "t_char": "?",
    "t_varchar": "??",
    "c_binary": "0x89504E470D0A1A0A0000000000000000",
    "c_varbinary": "0x89504E470D0A1A0A",
    "t_tinytext": "??tinytext",
    "t_text": "??text",
    "t_mediumtext": "??mediumtext",
    "t_longtext": "??longtext",
    "t_tinyblob": "tinyblob",
    "t_blob": "blob",
    "t_mediumblob": "mediumblob",
    "t_longblob": "longblob",
    "t_date": "1977-01-01",
    "t_datetime": "9999-12-31 23:59:59",
    "t_timestamp": "1973-12-30 23:30:00",
    "t_time": "23:59:59",
    "t_enum": "enum2",
    "t_set": "a,b",
    "t_bit": "0000000000000000000000000000000000000000000000000000000000000001",
    "t_json": null
  }
]
```
