### ISSUE TITLE
日志有完整DML内容，但是部分数据就是没同步过去

### ISSUE THREAD

**Issue by dingziyang** [alibaba/canal#4141]
## Question

> env: canal 1.1.4;  mysql 5.7; jdk1.8
> 场景： 从mysql同步到postgress
> 配置描述： 需要同步几个表，我在adapter的rdb目录下配了，一个表写一个yml文件

- 问题1：手动修改mysql数据时，每个表立刻会在adapter 的log中打印出DML(数据如下)， 但是只有某个表有数据同步进去(而且还不是实时）， 别的表的数据都没同步过去

- 问题2：我并没有给adapter指定配置的数据源，想问下adapter是不是有缓存？ 是本地h2吗？如果有缓存，有提供清理命令或接口吗？
- 问题3：我将一个已能成功同步的表的yml文件copy一份到同目录下，修改源表名和目标表名后，重启adapter时报错： Load canal adapter: rdb failed。。。。java.lang.RuntimeException: ERROR Config: warn_plan.yml dbMapping.table 
翻看源码是解析yml时失败，不知道是为什么？？

---

- adapter.log截取
```
2022-04-17 22:40:57.956 [pool-2-thread-1] INFO  c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"id":3984506,"client_id":"dyh-provider7069","topic":"dyh_mosquito/98D863E0CC8C","payload":"07-03-0C-00-01-00-00-00-00-00-00-00-00-00-00-11-EF-BF-BD-","mac":"98D863E0CC8C","payload_address":"07","payload_read_command":"03","payload_first_address":"0C00","payload_count":"0100","mosquito_count":null,"create_time":1650206457000,"density":0.0326}],"database":"dyh_bm","destination":"dyh_bm__pro-mysql","es":1650206457000,"groupId":null,"isDdl":false,"old":null,"pkNames":["id"],"sql":"","table":"mosquito_mqtt","ts":1650206457955,"type":"INSERT"}
2022-04-17 22:40:59.617 [pool-2-thread-1] INFO  c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"id":3984508,"client_id":"dyh-provider9841","topic":"dyh_mosquito/98D863E0CBAA","payload":"07-03-02-01-37-70-02-","mac":"98D863E0CBAA","payload_address":"07","payload_read_command":"03","payload_first_address":"0201","payload_count":"3770","mosquito_count":null,"create_time":1650206459000,"density":1.8079}],"database":"dyh_bm","destination":"dyh_bm__pro-mysql","es":1650206459000,"groupId":null,"isDdl":false,"old":null,"pkNames":["id"],"sql":"","table":"mosquito_mqtt","ts":1650206459616,"type":"INSERT"}
```

---

- adapter的application.yml
```
server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp
  canalServerHost: 172.34.41.41:11111
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://172.34.41.41:3306/srcdb?useUnicode=true&serverTimezone=GMT%2B8&nullNamePatternMatchesAll=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
      username: tertret
      password: 1qazXSW@
  canalAdapters:
  - instance: dyh_bm__pro-mysql # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: rdb
        key: postgres_dyh_center_db
        properties:
          jdbc.driverClassName: org.postgresql.Driver
          jdbc.url: jdbc:postgresql://172.34.41.111:5432/tardb
          jdbc.username: tertretertetetert
          jdbc.password: dfgdgdfgdfgdfgdfgf@2021
          threads: 1
          commitSize: 100
```

---

- 能成功的表配置（但是有几小时时延）mosquito_mqtt.yml
```
dataSourceKey: defaultDS
destination: dyh_bm__pro-mysql
groupId: g1
outerAdapterKey: postgres_dyh_center_db
concurrent: true
dbMapping:
  database: srcdb
  table: mosquito_mqtt
  targetTable: tardb.mosquito_mqtt
  targetPk:
    id: id
  mapAll: true
#  targetColumns:
#    id:
#    name:
#    role_id:
#    c_time:
#    test1:
#  etlCondition: "where c_time>={}"
  commitBatch: 500 # 批量提交的大小
```
