### ISSUE TITLE
adapter tcp模式乱序消费的问题

### ISSUE THREAD

**Issue by xesygao** [alibaba/canal#4325]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.6
* mysql version 5.7.0

### Issue Description
自己实现了两个adapter，使用tcp模式消费同一个instance，配置如下，启动之后会报错
batchId:1111 is not the firstly:1112
```
canalAdapters:
  - instance: sim # canal instance Name or mq topic name
    groups:
    - groupId: logSync
      outerAdapters:
      - name: log
        key: logSync
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver
          jdbc.url: jdbc:mysql://127.0.0.1:3306/xxx?useUnicode=true
          jdbc.username: root
          jdbc.password: xxxxx
          druid.stat.enable: false
          druid.stat.slowSqlMillis: 1000
    - groupId: redisSync
      outerAdapters:
      - name: redis
        key: redisSync
        properties:
          clusters: "127.0.0.1:8006,127.0.0.1:8007"
          timeout: 2000
          max-attempts: 3
          password: xxxxx
          pool:
            max-total: 32
            max-idle: 32
            min-idle: 0
```
猜测应该是乱序消费导致ack错乱。
查看代码发现在tcp模式下，同一个instance下配置两个group，会创建两个线程去消费server数据。按我的理解，一个instance只能对应一个consumer，猜测是多线程消费引发的乱序。而mq模式可以根据不同的groupId来创建不同的消费者组，相互之间没有影响。
所以修改了下com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader#init
有什么理解有误的地方烦请指正
```
/**
     * 初始化canal-client
     */
    public void init() {
        loader = ExtensionLoader.getExtensionLoader(OuterAdapter.class);

        /**
         * 多个instance/topic,tcp模式instance不能相同
         */
        List<String> instances=new ArrayList<>();
        for (CanalClientConfig.CanalAdapter canalAdapter : canalClientConfig.getCanalAdapters()) {
            /**
             * 多个groupId/groupName,mq模式支持多消费者组消费
             */
            if(!"tcp".equalsIgnoreCase(canalClientConfig.getMode())) {
                for (CanalClientConfig.Group group : canalAdapter.getGroups()) {
                    int autoGenId = 0;
                    List<List<OuterAdapter>> canalOuterAdapterGroups = new CopyOnWriteArrayList<>();
                    List<OuterAdapter> canalOuterAdapters = new CopyOnWriteArrayList<>();
                    /**
                     * 多个adapter
                     */
                    for (OuterAdapterConfig config : group.getOuterAdapters()) {
                        // 保证一定有key
                        if (StringUtils.isEmpty(config.getKey())) {
                            String key = StringUtils.join(
                                    new String[]{Util.AUTO_GENERATED_PREFIX, canalAdapter.getInstance(), group.getGroupId(),
                                            String.valueOf(autoGenId)},
                                    '-');
                            //gen keyId
                            config.setKey(key);
                        }
                        autoGenId++;
                        loadAdapter(config, canalOuterAdapters);
                    }
                    canalOuterAdapterGroups.add(canalOuterAdapters);

                    AdapterProcessor adapterProcessor = canalAdapterProcessors.computeIfAbsent(
                            canalAdapter.getInstance() + "|" + StringUtils.trimToEmpty(group.getGroupId()),
                            f -> new AdapterProcessor(canalClientConfig,
                                    canalAdapter.getInstance(),
                                    group.getGroupId(),
                                    canalOuterAdapterGroups));
                    adapterProcessor.start();

                    logger.info("Start adapter for canal-client mq topic: {} succeed",
                            canalAdapter.getInstance() + "-" + group.getGroupId());
                }
            } else {
                /**
                 * tcp模式一个instance只能有一个消费者
                 */
                if(instances.contains(canalAdapter.getInstance())){
                    logger.error("TCP mode do not allow consume more than one same instance, ignored");
                }else {
                    instances.add(canalAdapter.getInstance());
                    List<List<OuterAdapter>> canalOuterAdapterGroups = new CopyOnWriteArrayList<>();
                    /**
                     * 多个groupId/groupName,tcp模式只支持单消费者消费
                     */
                    for (CanalClientConfig.Group group : canalAdapter.getGroups()) {
                        int autoGenId = 0;
                        List<OuterAdapter> canalOuterAdapters = new CopyOnWriteArrayList<>();
                        /**
                         * 多个adapter
                         */
                        for (OuterAdapterConfig config : group.getOuterAdapters()) {
                            // 保证一定有key
                            if (StringUtils.isEmpty(config.getKey())) {
                                String key = StringUtils.join(
                                        new String[]{Util.AUTO_GENERATED_PREFIX, canalAdapter.getInstance(), group.getGroupId(),
                                                String.valueOf(autoGenId)},
                                        '-');
                                //gen keyId
                                config.setKey(key);
                            }
                            autoGenId++;
                            loadAdapter(config, canalOuterAdapters);
                        }
                        canalOuterAdapterGroups.add(canalOuterAdapters);
                    }
                    AdapterProcessor adapterProcessor = canalAdapterProcessors.computeIfAbsent(
                            canalAdapter.getInstance() + "|" + StringUtils.trimToEmpty("tcpMode"),
                            f -> new AdapterProcessor(canalClientConfig,
                                    canalAdapter.getInstance(),
                                    "tcpMode",
                                    canalOuterAdapterGroups));
                    adapterProcessor.start();

                    logger.info("Start adapter for canal-client mq topic: {} succeed",
                            canalAdapter.getInstance() + "-" + "tcpMode");
                }
            }
        }
    }
```

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
