### ISSUE TITLE
canal-adapter srcDataSources 配置多个源数据  ES无法同步第二个数据源数据

### ISSUE THREAD

**Issue by 1150549059** [alibaba/canal#4465]
问题：canal-adapter  中 srcDataSources 配置了2个数据源，canalAdapters 也配置了2个实例，但是只有一个ES同步成功，另一个日志打印正常，没有任何错误提示。

canal-adapter 中 application.yml 

```
server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
 
canal.conf:
  mode: tcp # 客户端的模式，可选tcp kafka rocketMQ
  flatMessage: true # 扁平message开关, 是否以json字符串形式投递数据, 仅在kafka/rocketMQ模式下有效
  zookeeperHosts:    # 对应集群模式下的zk地址
  syncBatchSize: 3000 # 每次同步的批数量
  retries: 0 # 重试次数, -1为无限重试
  timeout: # 同步超时时间, 单位毫秒
  accessKey:
  secretKey:
  consumerProperties:
    canal.tcp.server.host: 127.0.0.1:11111 #设置canal-server的地址
    canal.tcp.zookeeper.hosts:
    canal.tcp.batch.size: 500
    canal.tcp.username:
    canal.tcp.password:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://192.168.0.111:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: canal
      password: canal
    secondDS:
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: canal
      password: canal
  canalAdapters:
  - instance: example1 # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: es7
        key: exampleKey1
        hosts:  http://127.0.0.1:9200 # 127.0.0.1:9200 for rest mode
        properties:
          mode: rest # or rest
          #security.auth: elastic:Hna1rcom #  only used for rest mode
          cluster.name: elasticsearch
  - instance: example2 # canal instance Name or mq topic name
    groups:
    - groupId: g2
      outerAdapters:
      - name: logger
      - name: es7
        key: exampleKey2
        hosts:  http://127.0.0.1:9200 # 127.0.0.1:9200 for rest mode
        properties:
          mode: rest # or rest
          #security.auth: elastic:Hna1rcom #  only used for rest mode
          cluster.name: elasticsearch
```
配置文件 a.yml

```
dataSourceKey: defaultDS
outerAdapterKey: exampleKey1
destination: example1
groupId: g1
concurrent: true
esMapping:
_index: a
_id: id
sql: "select
id,
name,
create_date,
update_date
from
a"
commitBatch: 3000
```
配置文件 b.yml

```
dataSourceKey: secondDS
outerAdapterKey: exampleKey2
destination: example2
groupId: g2
concurrent: true
esMapping:
_index: b
_id: id
sql: "select
id,
name,
create_date,
update_date
from
b"
commitBatch: 3000
```
