### ISSUE TITLE
索引字段类型是text的字段无法同步

### ISSUE THREAD

**Issue by JamesZBL** [alibaba/canal#4598]
### environment

* canal version 1.1.6
* mysql version 5.7
* ES 7.x

### Issue Description

已验证能从MySQL同步到ES中，但是如果索引中字段配置的是 type: text，这个字段查询出来也同步不到ES中。

es7/xxx.yml
```
dataSourceKey: defaultDS
destination: example
outerAdapterKey: exampleKey
groupId: g1
esMapping:
  _index: xxx
  _id: _id
  _type: _doc
# upsert: true
#  pk: id
  sql: "SELECT g.spec_id AS _id, g.spec_name AS name, g.goods_name, g.modified AS modified FROM goods_shop_spec g"
#  objFields:
#    _labels: array:;
  etlCondition: "where g.modified >= {}"
  commitBatch: 3000
```

mapping:
```
{
    "properties": {
      "name": { "type": "text" },
      "goods_name": { "type": "text" },
      "modified": { "type": "date" }
    }
  }
```

查询结果：
```
{"_index":"xxx","_type":"_doc","_id":"327798","_version":4,"_seq_no":398,"_primary_term":1,"found":true,"_source":{"modified":"2023-02-10T16:05:51+08:00"}}
```

同步之后，查询出来只有 modified 字段，name、goods_name，这两个 text 类型的字段查不出来。
