### ISSUE TITLE
rdb同步未启动

### ISSUE THREAD

**Issue by okami-chen** [alibaba/canal#4600]
## Question

mysql 同步到Mysql，使用官方提供的docker部署,A实例的bitwarden_rs库，同步到B实例的bitwarden_rs库

canal-adapter成功监听到了变更,只是在日志中输出了，并没有同步到B实例。

```
2023-02-13 10:15:17.764 [pool-7-thread-1] INFO  c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":null,"database":"bitwarden_rs","destination":"west","es":1676254517000,"groupId":"g1","isDdl":false,"old":null,"pkNames":[],"sql":"UPDATE `users` SET `updated_at` = '2023-02-13 02:15:17.549281' WHERE `users`.`uuid` = 'f3fbd343-a001-4385-be42-9254e426a8f6'","table":"users","ts":1676254517668,"type":"UPDATE"}
```

**Comment by lxg07254698** [comment]
配置文件配错了，应该是没有具体到库或者表

**Comment by okami-chen** [comment]
> 配置文件配错了，应该是没有具体到库或者表
`rds/mysql1.yaml`
```
dataSourceKey: defaultDS
destination: west
groupId: g1
outerAdapterKey: mysql1
concurrent: true
dbMapping:
  mirrorDb: true
  database: bitwarden_rs
```

**Comment by okami-chen** [comment]
> 配置文件配错了，应该是没有具体到库或者表

`rds/mysql1.yaml`
```
dataSourceKey: defaultDS
destination: west
groupId: g1
outerAdapterKey: mysql1
concurrent: true
dbMapping:
  mirrorDb: true
  database: bitwarden_rs
```
`application.yaml`
```
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://192.168.196.30:3306/bitwarden_rs?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: sa
      password: N548SvToJ7SRPUh4
  canalAdapters:
    - instance: west # canal instance Name or mq topic name
      groups:
        - groupId: g1
          outerAdapters:
            - name: logger
            - name: rdb
              key: mysql1
              properties:
                jdbc.driverClassName: com.mysql.jdbc.Driver
                jdbc.url: jdbc:mysql://192.168.196.20:3306/bitwarden_rs?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
                jdbc.username: sa
                jdbc.password: N548SvToJ7SRPUh4
```
