### ISSUE TITLE
k8s部署canal-admin 数据保存不到canal_manager中

### ISSUE THREAD

**Issue by prclin** [alibaba/canal#4758]
### configmap
```
#configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: canal-admin-cm
  namespace: lattice
data:
  application.yaml: |
    server:
      port: 8089
    spring:
      jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8

    spring:
      datasource:
        address: mysql.lattice.svc.cluster.local:3306
        database: canal_manager
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://${spring.datasource.address}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
        hikari:
          maximum-pool-size: 30
          minimum-idle: 1
    canal:
      adminUser: admin
      adminPasswd: admin
```
挂载也是正确的
好像是canal-admin镜像内部有一个自启动的mysql
是只能用环境变量覆盖吗，像[wiki里说的那样](https://github.com/alibaba/canal/wiki/Canal-Admin-Docker)

**Comment by prclin** [comment]
已解决
1. 容器内默认配置文件为/home/admin/canal-admin/conf/application.yml
2. 由于configmap挂载只能为只读，所以需要将此configmap挂载到/etc目录下，在copy到/home/admin/canal-admin/conf/中来覆盖原有的文件
完整配置
```
#node port service
apiVersion: v1
kind: Service
metadata:
  name: canal-admin-np
  namespace: lattice
  labels:
    app: canal-admin
spec:
  type: NodePort
  selector:
    app: canal-admin
  ports:
    - name: web
      port: 8089
      targetPort: 8089
      nodePort: 30089
---
#configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: canal-admin-cm
  namespace: lattice
data:
  application.yml: |
    server:
      port: 8089
    spring:
      jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8

    spring:
      datasource:
        address: mysql.lattice.svc.cluster.local:3306
        database: canal_manager
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://${spring.datasource.address}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
        hikari:
          maximum-pool-size: 30
          minimum-idle: 1
    canal:
      adminUser: admin
      adminPasswd: admin
  startup.sh: |
    #要覆盖容器内默认提供的是/home/admin/canal-admin/conf/application.yml
    cp -f /etc/canal-admin/application.yml /home/admin/canal-admin/conf/application.yml
    /home/admin/app.sh
---
#StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: canal-admin
  namespace: lattice
spec:
  selector:
    matchLabels:
      app: canal-admin
  replicas: 1
  serviceName: canal-admin-np
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: canal-admin
    spec:
      containers:
        - name: canal-admin
          imagePullPolicy: IfNotPresent
          image: canal/canal-admin:v1.1.6
          ports:
            - name: web
              containerPort: 8089
          
          command: ["sh","/etc/canal-admin/startup.sh"]
          volumeMounts:
            - name: config
              mountPath: /etc/canal-admin
      volumes:
        - name: config
          configMap:
            name: canal-admin-cm
```
