### ISSUE TITLE
docker compose 部署的canal-server、canal-admin，canal-server注册不到canal-admin中

### ISSUE THREAD

**Issue by XiaoNing0430** [alibaba/canal#5272]
### canal-server配置
```yaml
# canal admin config
canal.admin.manager = canal-admin:8089
canal.admin.port = 11110
canal.admin.user = admin
canal.admin.passwd = 4ACFE3202A5FF5CF467898FC58AAB1D615029441
# admin auto register
canal.admin.register.auto = true
canal.admin.register.cluster = canal-single-node
canal.admin.register.name = 
```
### canal-admin配置
```yaml
spring.datasource:
  address: mysql-8.3.0:3306
  database: canal_manager
  username: canal
  password: canal
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://${spring.datasource.address}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  hikari:
    maximum-pool-size: 30
    minimum-idle: 1

canal:
  adminUser: admin
  adminPasswd: admin
```

### canal-server报错如下
![image](https://github.com/user-attachments/assets/fe548365-00cd-4fb0-9926-0ad3984d3259)
