### ISSUE TITLE
设置admin的上下文路径

### ISSUE THREAD

**Issue by HongKing** [alibaba/canal#5444]
目前设置上下文路径后，界面无法访问
```
server:
  port: 8089
  servlet:
    context-path: /canal
```
发现静态资源无法加载，还是走的根路径，应该是vue.config.js里面配置了绝对根路径
```
publicPath: '/',
改为
publicPath: './',
```
