### ISSUE TITLE
同一个MYSQL实例不同数据库之间的表同步

### ISSUE THREAD

**Issue by ieasyit** [alibaba/canal#5481]
按文档介绍，dbMapping.database的值代表源库和目标库的schema名称，即两库的schema要一模一样？
问题：不支持在同一个MYSQL实例 A 库到 B 库的表同步吗？因为同一个MYSQL实例不能创建相同的库名吧。我现在的需求是在同一个MYSQL实例 A 库到 B 库的表同步

**Comment by dcwendao** [comment]
你这个也许可以试试写一个触发器

**Comment by xuefun** [comment]
可以考虑加一层中间件，例如MQ   数据库A-canal-MQ-数据库B

**Comment by usedssl** [comment]
schema必须一样，源码里面会收到mq后解析成Ddl/dml数据，用的是mq消息里的database(源库名)，不能直接用canal-adapter ，可以改造也可以用canal-deploy + kafak(参考https://github.com/sunzsh/canaldemo)

**Comment by agapple** [comment]
canal-adapter 的 RDB 同步是支持**同一个 MySQL 实例中不同数据库之间的表同步**的。

`dbMapping` 中的 `database` 配置的是**源库的 schema 名称**，而目标库则通过 adapter 的 `dataSourceKey` 对应的 JDBC 连接来指定。具体做法：

**1. 配置两个数据源**

在 `application.yml` 中配置源库和目标库的数据源：
```yaml
canal.conf:
  srcDataSources:
    srcDS:
      url: jdbc:mysql://localhost:3306/db_a?useUnicode=true
      username: root
      password: xxx
  canalAdapters:
    - instance: example
      groups:
        - outAdapters:
            - name: rdb
              key: targetDS
              properties:
                jdbc.driverClassName: com.mysql.jdbc.Driver
                jdbc.url: jdbc:mysql://localhost:3306/db_b?useUnicode=true
                jdbc.username: root
                jdbc.password: xxx
```

**2. 配置表映射**

在 rdb 的映射配置文件中：
```yaml
dbMapping:
  database: db_a        # 源库 schema
  table: user           # 源表
  targetTable: db_b.user  # 目标库.目标表（可跨 schema 指定）
  targetPk:
    id: id
```

关键点是**目标表可以使用 `schema.table` 格式**来指定不同数据库中的表。

参考文档：https://github.com/alibaba/canal/wiki/Sync-RDB
